### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by KingNova82** [gucci-on-fleek/lockdown-browser#119]
### Common issues

- [x] If you get a "Terminal Services" error message, have you tried the troubleshooting steps [from the main instructions](https://github.com/gucci-on-fleek/lockdown-browser#you-get-a-terminal-services-error-message)?

- [x] If you get a "the setup configuration provider is not registered" error message, have you [installed the "Visual Studio C++ Tools"](https://github.com/gucci-on-fleek/lockdown-browser?tab=readme-ov-file#system-requirements)?

### Issue

Hello, I am unable to run the .\build.ps1

![Image](https://github.com/user-attachments/assets/3069f641-72f4-4b74-95f3-573f09c8aec4)

### Expected Behavior

I expected that the PowerShell script wouldn't give me this error message.

### Lockdown Browser Variant

Lockdown Browser (no webcam)

### Lockdown Browser Version

LockDownBrowser-2-1-3-00-536515735

### Windows Version and Build

Windows 10 22h2 19045.5440

### Repository version

N/A

**Comment by gucci-on-fleek** [comment]
Related to #116.

**Comment by Voidless7125** [comment]
> ### Common issues
> * [x] 
>   [x]  If you get a "Terminal Services" error message, have you tried the troubleshooting steps [from the main instructions](https://github.com/gucci-on-fleek/lockdown-browser#you-get-a-terminal-services-error-message)?
>   [x] 
>   [x]  If you get a "the setup configuration provider is not registered" error message, have you [installed the "Visual Studio C++ Tools"](https://github.com/gucci-on-fleek/lockdown-browser?tab=readme-ov-file#system-requirements)?
> 
> ### Issue
> Hello, I am unable to run the .\build.ps1
> 
> ![Image](https://github.com/user-attachments/assets/3069f641-72f4-4b74-95f3-573f09c8aec4)
> 
> ### Expected Behavior
> I expected that the PowerShell script wouldn't give me this error message.
> 
> ### Error Messages
> _No response_
> 
> ### Lockdown Browser Variant
> Lockdown Browser (no webcam)
> 
> ### Lockdown Browser Version
> LockDownBrowser-2-1-3-00-536515735
> 
> ### Windows Version and Build
> Windows 10 22h2 19045.5440
> 
> ### Repository version
> N/A
> 
> ### Other
> _No response_

Okay, I am working on reproducing it, but can you send the build logs from logs/build.log?

**Comment by Voidless7125** [comment]
Also, can you run Get-VSSetupInstance in PowerShell and send the output? It should look something like this:

PS C:\Users\Dominic\Desktop\Lockdown_Browser_Sandbox\DVT\lockdown-browser> Get-VSSetupInstance


InstanceId          : d551e56c
DisplayName         : Visual Studio Build Tools 2022
InstallationVersion : 17.12.35707.178
InstallationPath    : C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
InstallDate         : 1/29/2025 4:15:01 PM

(I have others installed but removed them because you only need this.)

**Comment by KingNova82** [comment]
> > ### Common issues
> > 
> > * [x]
> >   [x]  If you get a "Terminal Services" error message, have you tried the troubleshooting steps [from the main instructions](https://github.com/gucci-on-fleek/lockdown-browser#you-get-a-terminal-services-error-message)?
> >   [x]
> >   [x]  If you get a "the setup configuration provider is not registered" error message, have you [installed the "Visual Studio C++ Tools"](https://github.com/gucci-on-fleek/lockdown-browser?tab=readme-ov-file#system-requirements)?
> > 
> > ### Issue
> > Hello, I am unable to run the .\build.ps1
> > ![Image](https://github.com/user-attachments/assets/3069f641-72f4-4b74-95f3-573f09c8aec4)
> > ### Expected Behavior
> > I expected that the PowerShell script wouldn't give me this error message.
> > ### Error Messages
> > _No response_
> > ### Lockdown Browser Variant
> > Lockdown Browser (no webcam)
> > ### Lockdown Browser Version
> > LockDownBrowser-2-1-3-00-536515735
> > ### Windows Version and Build
> > Windows 10 22h2 19045.5440
> > ### Repository version
> > N/A
> > ### Other
> > _No response_
> 
> Okay, I am working on reproducing it, but can you send the build logs from logs/build.log?

[Build.log](https://github.com/user-attachments/files/18679821/Build.log)

**Comment by KingNova82** [comment]
> Also, can you run Get-VSSetupInstance in PowerShell and send the output? It should look something like this:
> 
> PS C:\Users\Dominic\Desktop\Lockdown_Browser_Sandbox\DVT\lockdown-browser> Get-VSSetupInstance
> 
> InstanceId : d551e56c DisplayName : Visual Studio Build Tools 2022 InstallationVersion : 17.12.35707.178 InstallationPath : C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools InstallDate : 1/29/2025 4:15:01 PM
> 
> (I installed others but removed them because you only need this.)

![Image](https://github.com/user-attachments/assets/2acf61eb-15ae-4861-95ac-3f8e7955095c)

**Comment by KingNova82** [comment]
![Image](https://github.com/user-attachments/assets/bb812e73-9902-495b-a7ad-d111195159db)

**Comment by Voidless7125** [comment]
> ![Image](https://github.com/user-attachments/assets/bb812e73-9902-495b-a7ad-d111195159db)

Thanks for the logs. Try installing visual studio community with no extras and see if the problem goes away. I still can't repo, but it could be that. 
If Visual Studio being installed fixes it, I'll patch it.

**Comment by KingNova82** [comment]
![Image](https://github.com/user-attachments/assets/f47a43f7-8bc8-4741-b0e2-53692d608471)

![Image](https://github.com/user-attachments/assets/2bfba4d3-db47-4599-bbe2-a0ee66ad1449)

**Comment by Voidless7125** [comment]
Are you still not able to build?

**Comment by KingNova82** [comment]
> Are you still not able to build?

Nope, still unable to build.

**Comment by gucci-on-fleek** [comment]
@Voidless7125 

> Try installing visual studio community with no extras and see if the problem goes away. 

That shouldn't be the issue, at least I don't think that it is.

> I still can't repo, but it could be that. If Visual Studio being installed fixes it, I'll patch it.

My random guess is that if there is only one instance of Visual Studio installed, instead of returning an array, `Get-VSSetupInstance` just returns the single object directly. So fixed code might look something like

```powershell
$vs = Get-VSSetupInstance
if (type($vs) == null) {
    error()
} elseif (type($vs) == array) {
    $vs = $vs[0]
}
if (type($vs) == vs_type_name) {
    do_stuff() 
} else {
    error()
}
```

**Comment by Voidless7125** [comment]
> [@Voidless7125](https://github.com/Voidless7125)
> 
> > Try installing visual studio community with no extras and see if the problem goes away.
> 
> That shouldn't be the issue, at least I don't think that it is.
> 
> > I still can't repo, but it could be that. If Visual Studio being installed fixes it, I'll patch it.
> 
> My random guess is that if there is only one instance of Visual Studio installed, instead of returning an array, `Get-VSSetupInstance` just returns the single object directly. So fixed code might look something like
> 
> $vs = Get-VSSetupInstance
> if (type($vs) == null) {
>     error()
> } elseif (type($vs) == array) {
>     $vs = $vs[0]
> }
> if (type($vs) == vs_type_name) {
>     do_stuff() 
> } else {
>     error()
> }

I have a (potential) fix, check my fork at https://github.com/Voidless7125/lockdown-browser

**Comment by Sanrax** [comment]
Same exact issue here. I also have Build Tools 2022 installed, with the latest MSVC and the latest Windows 11 SDK.

**Comment by Sanrax** [comment]
> > [@Voidless7125](https://github.com/Voidless7125)
> > > Try installing visual studio community with no extras and see if the problem goes away.
> > 
> > 
> > That shouldn't be the issue, at least I don't think that it is.
> > > I still can't repo, but it could be that. If Visual Studio being installed fixes it, I'll patch it.
> > 
> > 
> > My random guess is that if there is only one instance of Visual Studio installed, instead of returning an array, `Get-VSSetupInstance` just returns the single object directly. So fixed code might look something like
> > $vs = Get-VSSetupInstance
> > if (type($vs) == null) {
> > error()
> > } elseif (type($vs) == array) {
> > $vs = $vs[0]
> > }
> > if (type($vs) == vs_type_name) {
> > do_stuff()
> > } else {
> > error()
> > }
> 
> I have a (potential) fix, check my fork at https://github.com/Voidless7125/lockdown-browser

@Voidless7125, I tested your fork, and I get a length error instead. See screenshot:

![Image](https://github.com/user-attachments/assets/21170150-3203-4ba2-9c35-bbe1c1229c54)

**Comment by Voidless7125** [comment]
> > > [@Voidless7125](https://github.com/Voidless7125)
> > > > Try installing visual studio community with no extras and see if the problem goes away.
> > > 
> > > 
> > > That shouldn't be the issue, at least I don't think that it is.
> > > > I still can't repo, but it could be that. If Visual Studio being installed fixes it, I'll patch it.
> > > 
> > > 
> > > My random guess is that if there is only one instance of Visual Studio installed, instead of returning an array, `Get-VSSetupInstance` just returns the single object directly. So fixed code might look something like
> > > $vs = Get-VSSetupInstance
> > > if (type($vs) == null) {
> > > error()
> > > } elseif (type($vs) == array) {
> > > $vs = $vs[0]
> > > }
> > > if (type($vs) == vs_type_name) {
> > > do_stuff()
> > > } else {
> > > error()
> > > }
> > 
> > 
> > I have a (potential) fix, check my fork at https://github.com/Voidless7125/lockdown-browser
> 
> [@Voidless7125](https://github.com/Voidless7125), I tested your fork, and I get a length error instead. See screenshot:
> 
> ![Image](https://github.com/user-attachments/assets/21170150-3203-4ba2-9c35-bbe1c1229c54)
> 
> build.log contents below:
> 
> ```
> 2025-02-05 20:30:15 - ----------------------------------------
> 2025-02-05 20:30:15 - Build script started
> 2025-02-05 20:30:15 - Initializing Visual Studio environment
> 2025-02-05 20:30:15 - Error initializing Visual Studio environment: The property 'Length' cannot be found on this object. Verify that the property exists. -    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
>    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
>    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
>    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
> 2025-02-05 20:30:15 - Build script failed: The property 'Length' cannot be found on this object. Verify that the property exists. -    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
>    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
>    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
>    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
> ```
> 
> OS is Windows 10 Pro, 22H2.

Thanks for this. I still have no clue why it's erroring, its working on 4 pc's for me. I'll remove that check and let you know when I have the code ready.

**Comment by Voidless7125** [comment]
Okay. @Sanrax @KingNova82 I have just removed the checks on the fork. Pull the latest push and try again.
If you get any other errors please let me know!

**Comment by Voidless7125** [comment]
> [@Voidless7125](https://github.com/Voidless7125)
> 
> > Try installing visual studio community with no extras and see if the problem goes away.
> 
> That shouldn't be the issue, at least I don't think that it is.
> 
> > I still can't repo, but it could be that. If Visual Studio being installed fixes it, I'll patch it.
> 
> My random guess is that if there is only one instance of Visual Studio installed, instead of returning an array, `Get-VSSetupInstance` just returns the single object directly. So fixed code might look something like
> 
> $vs = Get-VSSetupInstance
> if (type($vs) == null) {
>     error()
> } elseif (type($vs) == array) {
>     $vs = $vs[0]
> }
> if (type($vs) == vs_type_name) {
>     do_stuff() 
> } else {
>     error()
> }

Yeah, that's a good idea. I (or you) have to repo, so I can test the fix in the first place.

**Comment by Sanrax** [comment]
> > [@Voidless7125](https://github.com/Voidless7125)
> > > Try installing visual studio community with no extras and see if the problem goes away.
> > 
> > 
> > That shouldn't be the issue, at least I don't think that it is.
> > > I still can't repo, but it could be that. If Visual Studio being installed fixes it, I'll patch it.
> > 
> > 
> > My random guess is that if there is only one instance of Visual Studio installed, instead of returning an array, `Get-VSSetupInstance` just returns the single object directly. So fixed code might look something like
> > $vs = Get-VSSetupInstance
> > if (type($vs) == null) {
> > error()
> > } elseif (type($vs) == array) {
> > $vs = $vs[0]
> > }
> > if (type($vs) == vs_type_name) {
> > do_stuff()
> > } else {
> > error()
> > }
> 
> Yeah, that's a good idea. I (or you) have to repo, so I can test the fix in the first place. Aha, they are all on Win 10, while I am [@gucci-on-fleek](https://github.com/gucci-on-fleek) are on Win 11.

Wait, are we just being dumb then? Should we install Windows 10 SDK instead of 11?

**Comment by Voidless7125** [comment]
> > > [@Voidless7125](https://github.com/Voidless7125)
> > > > Try installing visual studio community with no extras and see if the problem goes away.
> > > 
> > > 
> > > That shouldn't be the issue, at least I don't think that it is.
> > > > I still can't repo, but it could be that. If Visual Studio being installed fixes it, I'll patch it.
> > > 
> > > 
> > > My random guess is that if there is only one instance of Visual Studio installed, instead of returning an array, `Get-VSSetupInstance` just returns the single object directly. So fixed code might look something like
> > > $vs = Get-VSSetupInstance
> > > if (type($vs) == null) {
> > > error()
> > > } elseif (type($vs) == array) {
> > > $vs = $vs[0]
> > > }
> > > if (type($vs) == vs_type_name) {
> > > do_stuff()
> > > } else {
> > > error()
> > > }
> > 
> > 
> > Yeah, that's a good idea. I (or you) have to repo, so I can test the fix in the first place. Aha, they are all on Win 10, while I am [@gucci-on-fleek](https://github.com/gucci-on-fleek) are on Win 11.
> 
> Wait, are we just being dumb then? Should we install Windows 10 SDK instead of 11?

It shouldent matter, but feel free to try. Sorry I am asking again, but I just pushed the update to my fork without the check.

**Comment by Sanrax** [comment]
> > > > [@Voidless7125](https://github.com/Voidless7125)
> > > > > Try installing visual studio community with no extras and see if the problem goes away.
> > > > 
> > > > 
> > > > That shouldn't be the issue, at least I don't think that it is.
> > > > > I still can't repo, but it could be that. If Visual Studio being installed fixes it, I'll patch it.
> > > > 
> > > > 
> > > > My random guess is that if there is only one instance of Visual Studio installed, instead of returning an array, `Get-VSSetupInstance` just returns the single object directly. So fixed code might look something like
> > > > $vs = Get-VSSetupInstance
> > > > if (type($vs) == null) {
> > > > error()
> > > > } elseif (type($vs) == array) {
> > > > $vs = $vs[0]
> > > > }
> > > > if (type($vs) == vs_type_name) {
> > > > do_stuff()
> > > > } else {
> > > > error()
> > > > }
> > > 
> > > 
> > > Yeah, that's a good idea. I (or you) have to repo, so I can test the fix in the first place. Aha, they are all on Win 10, while I am [@gucci-on-fleek](https://github.com/gucci-on-fleek) are on Win 11.
> > 
> > 
> > Wait, are we just being dumb then? Should we install Windows 10 SDK instead of 11?
> 
> It shouldent matter, but feel free to try. Sorry I am asking again, but I just pushed the update to my fork without the check.

![Image](https://github.com/user-attachments/assets/68c25ad1-a421-40a8-a8b3-0e1a1dcf5aec)

**Comment by Voidless7125** [comment]
That would mean that vs build tools aren't insalled correctly.

![Image](https://github.com/user-attachments/assets/966a2dc2-3d06-4136-8a02-99657631a9d3)

But that is weird. OP had output for Get-VSSetupInstance, and it still failed.
I just revirted the build.ps1 to a older version that works. There is NO file logging, but you'll see it in the terminal.

**Comment by Sanrax** [comment]
I installed Win 10 SDK, and I still get the nmake error.

Will try a reboot and test, without pulling latest changes again.

**Comment by Sanrax** [comment]
Reboot doesn't help, but @Voidless7125, are you able to run `nmake` from PowerShell and get output?

I simply get told the program can't be found, but it's there in Program Files.

I can fix the issue by adding it to PATH, but that seems to only fix a part of the issue.

**Comment by Voidless7125** [comment]
> Reboot doesn't help, but [@Voidless7125](https://github.com/Voidless7125), are you able to run `nmake` from PowerShell and get output?
> 
> I simply get told the program can't be found, but it's there in Program Files.
> 
> I can fix the issue by adding it to PATH, but that seems to only fix a part of the issue.

dont need to add it to the path, its in the visual studio install and the powershell file gets it from there. 
(and I dont have it in path so it will error for me in powershell, but the build works fine)
Which ever is easyer for you, if you have discord I have the same username here as on discord, and you (or me) can share screen and see whats going on. (Or I can send a video of what should happen)

**Comment by Sanrax** [comment]
But that is weird. OP had output for Get-VSSetupInstance, and it still failed. Try adding that to Visual Studio Community 2022 and reboot. I had a simaller nmake problem that got fixed in a roboot. (And the Get-VSSetupInstance prob needs a reboot to work.) I just revirted the build.ps1 to a older version that works. There is NO file logging, but you'll see it in the terminal

I reverted my PATH changes, pulled latest changes from fork, and ran build.ps1:

```
PS C:\Users\XXX\Downloads\lockdown-browser> .\build.ps1
'.\VC\Auxiliary\Build\vcvars32.bat' is not recognized as an internal or external command,
operable program or batch file.
nmake : The term 'nmake' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
At C:\Users\XXX\Downloads\lockdown-browser\build.ps1:40 char:5
+     nmake
+     ~~~~~
    + CategoryInfo          : ObjectNotFound: (nmake:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\XXX\Downloads\lockdown-browser\Detours\src>
```

**Comment by Sanrax** [comment]
> > Reboot doesn't help, but [@Voidless7125](https://github.com/Voidless7125), are you able to run `nmake` from PowerShell and get output?
> > I simply get told the program can't be found, but it's there in Program Files.
> > I can fix the issue by adding it to PATH, but that seems to only fix a part of the issue.
> 
> dont need to add it to the path, its in the visual studio install and the powershell file gets it from there. (and I dont have it in path so it will error for me in powershell, but the build works fine) Which ever is easyer for you, if you have discord I have the same username here as on discord, and you (or me) can share screen and see whats going on. (Or I can send a video of what should happen)

Discord is fine, will send request.

**Comment by gucci-on-fleek** [comment]
The latest commit (9ca6eb52c2f14c217589082a39f22e57366317e3) should fix this (although I haven't actually tested it yet), but if that doesn't work, you can switch to the latest stable version with `git switch --detach v1.3.0`.

**Comment by Sanrax** [comment]
@KingNova82, I was able to build the project on Windows 10 by installing the following in VS 2022 Build Tools setup:

![Image](https://github.com/user-attachments/assets/44f60dfa-b320-419b-b7ad-3b09b7be5175)

This shows up in the installer sidebar for installed components:

![Image](https://github.com/user-attachments/assets/299abc63-a3f0-49df-bf2c-52b1c7cc1ecf)

Before doing this, I did not have `vcvars32.bat` in `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build`

Once you have the file, you should be good to go. This is what I have at that path:

![Image](https://github.com/user-attachments/assets/71a2082b-d7b0-41ce-98cd-03fcaf83cc87)

**Comment by Voidless7125** [comment]
So this has been fixed. For Windows 10 installs, that conponent is needed for this to work. (Tested in a win10 vm)
Something changed at microsoft's build tools because using a older version does not have this problem. 
Windows 11 isen't effected.

**Comment by gucci-on-fleek** [comment]
@Sanrax 

> I was able to build the project on Windows 10 by installing the following in VS 2022 Build Tools setup:
> 
> ![Image](https://github.com/user-attachments/assets/44f60dfa-b320-419b-b7ad-3b09b7be5175)
> 
> This shows up in the installer sidebar for installed components:
> 
> ![Image](https://github.com/user-attachments/assets/299abc63-a3f0-49df-bf2c-52b1c7cc1ecf)

Which of those components _didn't_ you have installed before?

**Comment by Sanrax** [comment]
> [@Sanrax](https://github.com/Sanrax)
> 
> > I was able to build the project on Windows 10 by installing the following in VS 2022 Build Tools setup:
> > ![Image](https://github.com/user-attachments/assets/44f60dfa-b320-419b-b7ad-3b09b7be5175)
> > This shows up in the installer sidebar for installed components:
> > ![Image](https://github.com/user-attachments/assets/299abc63-a3f0-49df-bf2c-52b1c7cc1ecf)
> 
> Which of those components _didn't_ you have installed before?

When it didn't work for me, I did the following:

1. Download Build Tools exe
2. Run setup exe
3. Go to Individual Components
4. Select latest MSVC, Windows 10 SDK, and Windows 11 SDK
5. Install components
6. Run build.ps1, fails
